services:
  - type: web
    name: llm-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: ./render_start.sh

  - type: static
    name: llm-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
